---
version: 0.2
phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      # helm
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      #
      - export PATH=$PWD/:$PATH
  pre_build:
      commands:
        - TAG="$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
        - git clone https://$GITHUB_USERNAME:GITHUB_PASSWORD@github.com/mahmoud254/cats-helm-chart.git
        - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY:$TAG"'@' cats-helm-chart/values.yaml
        - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - docker build --tag $REPOSITORY:$TAG .

  post_build:
    commands:
      - docker push $REPOSITORY:$TAG
      - helm package cats-helm-chart -d cats-helm-chart/
      - helm repo index cats-helm-chart --url $HELM_REPOSITORY
      - cd cats-helm-chart && git add . && git commit -m auto-deployment-$TAG && git push 
      - printf '[{"name":"eks-deployment","imageUri":"%s"}]' $REPOSITORY:$TAG > build.json
artifacts:
  files: build.json