
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: Kubernetes/dev
    repoURL: "https://github.com/mahmoud254/redis-backend-demo.git"
    targetRevision: HEAD
    directory:
      exclude: '{secrets.yml,env.py}'
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true